Numpy (Numerical python)

It's a python library use for working with arrays. An array is like a list, but it an store large amounts of data much more efficiently

Python lists can be slow and take up more memory when working with large data but NumPy helps solve this problem by: 

   - storing data efficiently
       
   - performing calculations faster
       
   - Offering built-in functions for common mathematical and statiscal operations
       
Arrays are important in data science they allow you to share data in two-dimentional or multi-dimentional forms, similar to rows and columns in a spreadsheet 

Numpy arrays can be used to perfroms operation one entire arrays at once instead of hoping through elements one by one  

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
e = [i for i in range (2,50) if i%2 == 0]
o = [i for i in range (2,50) if i%2 != 0]

print(e)
print(o)
     

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [6]:
# Scaling to list 
a = e + o
print(a)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [7]:
r= []

for i in range (len(e)):
    r.append(e[i] * o[1])
    
print(r)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]


In [8]:
# using list comprehension elements of the two lists can be paired using the zip() function 

r = [x * y for x, y in zip(e, o)]
print (r)

[6, 20, 42, 72, 110, 156, 210, 272, 342, 420, 506, 600, 702, 812, 930, 1056, 1190, 1332, 1482, 1640, 1806, 1980, 2162, 2352]


Creating an array 

In [10]:
np.array ([5, 4, 66, 7, 8, 2, 1, 5, 8, 99])

array([ 5,  4, 66,  7,  8,  2,  1,  5,  8, 99])

In [11]:
np. array ([7, 9, 11, 14, 17, 20, 25, 28, 35])

array([ 7,  9, 11, 14, 17, 20, 25, 28, 35])

In [12]:
b = np.array(e)
d = np.array(o)

print(b)
print(d)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


Array Operation

In [14]:
b+d

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69,
       73, 77, 81, 85, 89, 93, 97])

In [15]:
np.mean([d])

26.0

In [16]:
np.sum([b])

600

In [17]:
y = b/d
print(y)

[0.66666667 0.8        0.85714286 0.88888889 0.90909091 0.92307692
 0.93333333 0.94117647 0.94736842 0.95238095 0.95652174 0.96
 0.96296296 0.96551724 0.96774194 0.96969697 0.97142857 0.97297297
 0.97435897 0.97560976 0.97674419 0.97777778 0.9787234  0.97959184]


In [18]:
# to summarize the decimals
np.around(y, decimals = 2)

array([0.67, 0.8 , 0.86, 0.89, 0.91, 0.92, 0.93, 0.94, 0.95, 0.95, 0.96,
       0.96, 0.96, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.98, 0.98, 0.98,
       0.98, 0.98])

In [19]:
y.shape

(24,)

 ## Array dimensions
Axes Direction along the data is arraged 
    
    - 1D array or 1 axis
       
    - 2D array has 3 axes rows and columns 
        
    - 3D array has 3 axes layers,rows and columns

In [21]:
np.array ([[b], [d]])

array([[[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
         34, 36, 38, 40, 42, 44, 46, 48]],

       [[ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
         35, 37, 39, 41, 43, 45, 47, 49]]])

In [22]:
d = np.array([[b], [d], [e]])

print(d)

[[[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
   48]]

 [[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
   49]]

 [[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
   48]]]


In [23]:
print(d.shape)
print(d.ndim)
print(d.size)

(3, 1, 24)
3
72


In [24]:
j = np.array([[7,8,9,8,0],[8,6,5,78,9]])
print(j.shape)
print(j)

(2, 5)
[[ 7  8  9  8  0]
 [ 8  6  5 78  9]]


In [25]:
j.ndim

2

In [26]:
# To create a 2D array with 20 elements (4 rows, 5 columns)
l =np.arange(20).reshape(4, 5)
print(l.shape)
print(l)

(4, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [28]:
np.arange(1,37).reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [29]:
q = np.arange(12).reshape(2, 3, 2)
print(q)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [30]:
np.transpose(np.arange (1,37).reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [31]:
l[3]

array([15, 16, 17, 18, 19])

In [32]:
# accessing an element using its row and column index

l[1,3]

8

In [33]:
l[2]*l[0]

array([ 0, 11, 24, 39, 56])

In [34]:
l[3] + y[3]

array([15.88888889, 16.88888889, 17.88888889, 18.88888889, 19.88888889])

In [35]:
q[0]
q[0,2]
q[1,2,1]

11

In [36]:
q[0,2]

array([4, 5])

### List of data types in NumPy and the characters used to represent them.
 - s -string
 - I -integer
 - b -boolean
 - f -float
 - c -complex float
 - m -timedelta
 - M -datetime
 - O -object
 - u -unicode string
 - v -fixed chuck of memory for other type (void)
   - size can be defined for i,u,f,s and U

In [38]:
q.dtype

dtype('int32')

In [39]:
# specifying the data type of an array
v = np.array([1,2,3,4], dtype="S")
print(v)

[b'1' b'2' b'3' b'4']


In [40]:
v.dtype

dtype('S1')

In [41]:
v.astype(int)

array([1, 2, 3, 4])

## Some of the most important NumPy method. 

1. Creating Arrays 

    - a. np.array() to create Numpy array from a python list or tuple
     
    - b. np.zeros(), np.ones(), np.full() create arrays filled with zeros,ones or a specific value
     
    - c. np.arrange(), np.lenspace() create arrays of evenly spaced values 

In [43]:
np.array([[3, 6, 8, 9, 7, 12],[7, 2, 8, 9.7, 4, 12] ])

array([[ 3. ,  6. ,  8. ,  9. ,  7. , 12. ],
       [ 7. ,  2. ,  8. ,  9.7,  4. , 12. ]])

In [44]:
np.zeros((3, 15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros((14,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.ones ((4, 20))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [47]:
np.zeros(((4, 2, 2)))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [48]:
np.full((3, 4, 4), 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [49]:
np.full((3, 4, 4), 1)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [50]:
np.arange(0, 27) # start, stop, step

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [51]:
np.arange(0, 27, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [52]:
np.arange(0, 27, 4)

array([ 0,  4,  8, 12, 16, 20, 24])

In [53]:
np.linspace(2, 10) 

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [54]:
p = np.linspace(2, 10, 8) #(start, stop, num_points)

In [55]:
np.round(p, decimals = 3) # reducing the decimal number into 3 decimal places

array([ 2.   ,  3.143,  4.286,  5.429,  6.571,  7.714,  8.857, 10.   ])

### 2. Reshaping and Manipulating Arrays

 - np.reshape(): reshapes an array without changing its data
    
 - np.ravel(), np.flatter() converts multi-dim arrays into 10 arrays, ravels() returns a view and flatter() returns a copy
        
 - np.transpose() reverse or permutes the axes of an arrays often usedd with matrices 

In [57]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [58]:
b.reshape(2,6,2)

array([[[ 2,  4],
        [ 6,  8],
        [10, 12],
        [14, 16],
        [18, 20],
        [22, 24]],

       [[26, 28],
        [30, 32],
        [34, 36],
        [38, 40],
        [42, 44],
        [46, 48]]])

In [59]:
p = np.arange(0, 100).reshape(10, 10)
print(p)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [60]:
p.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
np.ravel(p)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
G =np.arange(2, 50)

In [63]:
print(G)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [64]:
np.arange(1, 25, 3).reshape(2,4)

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [65]:
j.reshape(5,2)

array([[ 7,  8],
       [ 9,  8],
       [ 0,  8],
       [ 6,  5],
       [78,  9]])

In [66]:
np.ravel(j)

array([ 7,  8,  9,  8,  0,  8,  6,  5, 78,  9])

In [67]:
l.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
j.flatten()

array([ 7,  8,  9,  8,  0,  8,  6,  5, 78,  9])

In [69]:
G.reshape(3, 16)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
np.transpose(l)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [71]:
l

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
p.transpose()

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

### 3. Basic Math and Statistics Operations

- np.sum(), np.mean(),np.meadian(): compute the sum, mean, and median of an array.
- np.max(), np.min(), np.argmax(),np.argmin(): find the maximum, minimum values and their indices in an array.
- np.cumsum(),np.cumprod(): return the cummulative sum or product along an array

In [75]:
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [141]:
j.std()

21.549013898552296

In [145]:
np.sum(j)

138

In [147]:
p.sum()

4950

In [149]:
# summing two array
b+d

array([[[ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
         68, 72, 76, 80, 84, 88, 92, 96]],

       [[ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
         69, 73, 77, 81, 85, 89, 93, 97]],

       [[ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
         68, 72, 76, 80, 84, 88, 92, 96]]])

In [151]:
# adding a number to every element in an array - vectorization 
b + 10

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50, 52, 54, 56, 58])

In [157]:
# Indexing
b[4]+b[23]

58

In [171]:
 b[5]+b[8]

30

In [173]:
b[2]+b[0]

8

In [175]:
b[2]+p[0]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [179]:
b[2]+p[0,2]

8

In [159]:
p.min()

0

In [181]:
p.max()

99

In [161]:
v.argmin()

0

In [183]:
v.argmax()

3

In [185]:
b.cumsum()

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156, 182,
       210, 240, 272, 306, 342, 380, 420, 462, 506, 552, 600])

In [167]:
p.cumsum()

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926,
       3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828,
       3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851,
       4950])

In [169]:
p.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [187]:
b.cumprod()

array([          2,           8,          48,         384,        3840,
             46080,      645120,    10321920,   185794560,  -579076096,
         145227776,  -809500672,   427819008,  -905969664, -1409286144,
       -2147483648,           0,           0,           0,           0,
                 0,           0,           0,           0])

In [191]:
v = np.array(v, dtype=np.float64)

In [193]:
v

array([1., 2., 3., 4.])

In [195]:
v.cumprod()

array([ 1.,  2.,  6., 24.])

### 4. Sorting and Logical Operation 

- np.sort()
- np.where(): Return the indicies of elements that satify a condition.
- np.any(), and np.all(): Tests whether any or all elements of an array evaluate to True

In [207]:
j.shape

(2, 5)

In [209]:
np.sort(j)

array([[ 0,  7,  8,  8,  9],
       [ 5,  6,  8,  9, 78]])

In [211]:
np.where(j == 8)

(array([0, 0, 1], dtype=int64), array([1, 3, 0], dtype=int64))

In [213]:
np.where(j>6)

(array([0, 0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 3, 4], dtype=int64))

In [217]:
#First array(array([0,0,0,0,1,1,1],dtype = int64)): are the row indices where the condition j > 6 is true.
#second array (array([0,1,2,3,0,3,4], dtype= int64)): are the column indices where the condition is true.

j[0,0] =7
j[0,1] =8
j[0,2] =9
j[0,3] =8
j[1,0] =8
j[1,3] =78
j[1,4] =9
    

In [219]:
j[j>6]

array([ 7,  8,  9,  8,  8, 78,  9])

In [221]:
p[p<=5]

array([0, 1, 2, 3, 4, 5])

In [223]:
p[p>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [225]:
b[b==30]

array([30])

In [227]:
d[d!=31]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21,
       23, 25, 27, 29, 33, 35, 37, 39, 41, 43, 45, 47, 49,  2,  4,  6,  8,
       10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [229]:
[b[b>30],d[d>31]]

[array([32, 34, 36, 38, 40, 42, 44, 46, 48]),
 array([32, 34, 36, 38, 40, 42, 44, 46, 48, 33, 35, 37, 39, 41, 43, 45, 47,
        49, 32, 34, 36, 38, 40, 42, 44, 46, 48])]

In [237]:
np.intersect1d(b, v)

array([2., 4.])

In [239]:
np.any(j>0)

True

In [241]:
np.all(j>0)

False

### 5. Removing Elements from an Array

- np.delete()

In [247]:
np.delete(b,[2,10])

array([ 2,  4,  8, 10, 12, 14, 16, 18, 20, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48])

In [ ]:
np.delete(b,[2,10])

In [251]:
np.delete(b,np.arange(2, 7, 8))

array([ 2,  4,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48])

In [253]:
p.shape

(10, 10)

In [255]:
# Removing rows and columns from a 2D Array
np.delete(p, 1, axis=0) # axis=0 for rows

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [257]:
np.delete(p, 1, axis=1)# axis=1 for columns

array([[ 0,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 92, 93, 94, 95, 96, 97, 98, 99]])

In [259]:
np.delete(v, 1, axis=0)

array([1., 3., 4.])

In [261]:
# for 3D
np.delete(v, 0, axis =0)

array([2., 3., 4.])

### 6. Joining and appending array(x)

- np.concatenate(): used to join two or more array along an existing axis, doesn't add new dimensions- just extends the array along the specified axis
- np.stack(): is used to join array along a nex axis. This is different from concatenation because it creates a new dimension in the resulting array
- np.append()

In [267]:
np.append(b, 7)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48,  7])

In [273]:
q = np.arange(1, 21).reshape(2, 10)
q

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [275]:
np.concatenate((p,q), axis = 0) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [277]:
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [284]:
np.append(b, [3,4,5,6])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48,  3,  4,  5,  6])

In [286]:
np.append(p, np.arange(0, 10))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9])

### 7. Splitting array
- np.split(): splits an array into multiple sub-array eually along a specified axis.
- np.array_split(): is a more flexible version of np.split() because it allows unequal splits 

In [289]:
np.split(b, 4)

[array([ 2,  4,  6,  8, 10, 12]),
 array([14, 16, 18, 20, 22, 24]),
 array([26, 28, 30, 32, 34, 36]),
 array([38, 40, 42, 44, 46, 48])]

In [291]:
np.split(p, 2, axis=1)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [293]:
np.hsplit(p,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [295]:
np.split(p, 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [297]:
np.vsplit(p,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [303]:
np.array_split(p, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [10, 11, 12, 13],
        [20, 21, 22, 23],
        [30, 31, 32, 33],
        [40, 41, 42, 43],
        [50, 51, 52, 53],
        [60, 61, 62, 63],
        [70, 71, 72, 73],
        [80, 81, 82, 83],
        [90, 91, 92, 93]]),
 array([[ 4,  5,  6],
        [14, 15, 16],
        [24, 25, 26],
        [34, 35, 36],
        [44, 45, 46],
        [54, 55, 56],
        [64, 65, 66],
        [74, 75, 76],
        [84, 85, 86],
        [94, 95, 96]]),
 array([[ 7,  8,  9],
        [17, 18, 19],
        [27, 28, 29],
        [37, 38, 39],
        [47, 48, 49],
        [57, 58, 59],
        [67, 68, 69],
        [77, 78, 79],
        [87, 88, 89],
        [97, 98, 99]])]

### 8. Random Number Generation
- np.random.rand() and np.random.randint()generates random numbes (float and integers).

In [306]:
np.random.rand(4)

array([0.6431588 , 0.41521518, 0.95287451, 0.5624022 ])

In [308]:
np.random.rand(4).round(2)

array([0.91, 0.46, 0.73, 0.84])

In [318]:
np.random.rand(20)

array([0.62045742, 0.94326148, 0.83833207, 0.03495213, 0.41007902,
       0.12384016, 0.46038301, 0.88493803, 0.41821343, 0.18171478,
       0.09136493, 0.61818092, 0.03553109, 0.27310198, 0.98136814,
       0.06849671, 0.38389668, 0.66567091, 0.26162381, 0.67094655])

In [310]:
np.round(np.random.rand(4), decimals =2)

array([0.46, 0.25, 0.36, 0.33])

In [312]:
np.random.randint(50, 100, 5)

array([59, 86, 62, 95, 92])

In [314]:
np.random.randint(50, 100, 55)

array([96, 54, 52, 77, 72, 83, 55, 96, 50, 92, 68, 65, 65, 82, 96, 95, 63,
       63, 86, 99, 77, 85, 72, 89, 90, 51, 50, 73, 81, 97, 61, 86, 72, 54,
       54, 51, 81, 87, 96, 74, 87, 57, 67, 67, 84, 61, 56, 91, 60, 61, 85,
       84, 83, 66, 54])